### ISSUE TITLE
Audio Issue

### ISSUE THREAD

**Issue by Appswage** [khoavd-dev/MergeVideos#2]
I found that the audio would cut-off in the second merged video. I believe the issue is with the implementation of the `audioCompositionTrack`. For that the startTime should be `kCMTimeZero` in all cases. Here is the correction I made which fixed the issue:

 // Add audio track to audio composition at specific time

                if let audioTrack = audioTrack {
                    try audioCompositionTrack?.insertTimeRange(CMTimeRangeMake(startTime, duration),
                                                               of: audioTrack,
                                                               at: insertTime)
                }

**Comment by khoavd-dev** [comment]
@Appswage Great!!! Thank you for pointing out this issue. It was my mistake.
I fixed it. (commit: 90114e9ccab260fa589e9269d27dcb83bf7f68c9)
